apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: registrysecret
      volumes:
      - name: secret
        secret:
          secretName: {{ .Chart.Name }}-tls
          defaultMode: 0400
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        imagePullPolicy: IfNotPresent
        command: ["/app/start.sh"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secret
          mountPath: "/etc/secret"
          readOnly: true
        env:
          - name: TLS_CRT
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}-tls
                key: tls.crt
                optional: false
          - name: TLS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}-tls
                key: tls.key
                optional: false
